description: 'Default Deployment plan

  '
environments:
- path: overcloud-resource-registry-puppet.yaml
- path: environments/containers-default-parameters.yaml
name: overcloud
passwords:
  AdminPassword: meTvKwmdvHqFGUGPyJbRa8pGT
  AdminToken: 4dnTfevVKGygvVQ6zEeUzymRA
  AodhPassword: hrffzVwVwK8CdfhbMJ9K8MggF
  BarbicanPassword: 8WjNUuPTYrqxVtnbdnPfFQ4WP
  BarbicanSimpleCryptoKek: GTI5e2pXIaL_9OSszj4A65W0kzbsBhiZqryospM2TYs=
  CeilometerMeteringSecret: hJwQsHBdsm6baFKDuqrAUxJDX
  CeilometerPassword: 9BZjRryzwfrAxVcXXaGzNvWtE
  CephAdminKey: AQCZrQVbAAAAABAAmGLPOsakCq2osns6NAEBOA==
  CephClientKey: AQCZrQVbAAAAABAAEbV6T8lVsIdm0f1A8atTFg==
  CephClusterFSID: fcea6e30-5eb3-11e8-94ab-525400569a1b
  CephManilaClientKey: AQCZrQVbAAAAABAAhT3+Q4XGd1d5TZ8szTjGDQ==
  CephMdsKey: AQCZrQVbAAAAABAArqsZ7VkMmrnv6Zk/B5hEGg==
  CephMonKey: AQCZrQVbAAAAABAAc/K8yMI5eJd8yhivjadsfQ==
  CephRgwKey: AQCZrQVbAAAAABAASLV1cgUtftxhO68wicKWbw==
  CinderPassword: y7uTYGVZvHq7BHkKPWGg7fQeC
  CongressPassword: K8whjYraKTkCsgZHfbjrj6YPQ
  DesignatePassword: k4BKdghxPTuDfyC7tudBbxHs9
  Ec2ApiPassword: v8Bw4nqB9vUvgVCXeXvtvcTUh
  EtcdInitialClusterToken: KUCbx4WGKHe84WpJuGm6wypPK
  GlancePassword: mXKba7rb6zVqcNAuhERqCkTUu
  GnocchiPassword: FCR92rZ2NpEzCmxfjEewUcMfM
  HAProxyStatsPassword: YusAFjCMtnxqUXGFUHCTBvAWE
  HeatAuthEncryptionKey: nzxNQ9kqzkADvhHW8QPdrq7n3tNU4edN
  HeatPassword: vZzYxpjC6tX8WENnB2en7kbmc
  HeatStackDomainAdminPassword: sAxnwZnf6yuPMk7ERa8DagxYR
  HorizonSecret: eAnk4bMgh2
  IronicPassword: 4ku6frrgnJB7zfWqhauT22hHF
  KeystoneCredential0: lVLHQ-YpWL5Mceb2gphez1uhEaP60fO12bskV-JCl9Y=
  KeystoneCredential1: wqXPgiQoblLlhv0qYe3WnCzIMy1HKn2h9uJx4zGlxZw=
  KeystoneFernetKey0: AtPOtYC2KhezrCHJqUo5aMv9vSesYgyL2NG3S4g3FjM=
  KeystoneFernetKey1: qZixXKCtbvLLDfjq1V26X64FV7MGsVRMFO27g2u1oG0=
  KeystoneFernetKeys:
    /etc/keystone/fernet-keys/0:
      content: 0iGDl3I6J8cf-4Bm4UTwv9_FzaFZ6bMO0aOMNxXOBDk=
    /etc/keystone/fernet-keys/1:
      content: aJqsG1XJCgBG_nf2dpLifAqOFqnaROwJXExEpwQ0GFQ=
  LibvirtTLSPassword: JPYM8mZMG87f4xP2DwXTfjHVt
  ManilaPassword: bqHCepuGjAqndb7VBRYuGCVQy
  MigrationSshKey:
    private_key: '-----BEGIN RSA PRIVATE KEY-----

      MIIEowIBAAKCAQEAvovAxsa5UGmyAnQD11LEw1bvqMo98nVqLMy8uFxRAonitcr8

      VuUOYhy0ykdotLENW5+CoihmRQrakdvwbll1F53kSTICUHwsOJOTEkqoLXtalInr

      NyUjZrnpDChd5pgJEtEQrBQ5x1XmYfYjnyKTnBL3jhk75LlQGA6S9FMgqB8zaymx

      jLH1NdvVZJyo7uzF5olYwSP4H8g+N66Wu/4CVlYhXzfif2XWX63Dzr03zwWYQfY1

      ZQWIaOaU3B8mTSGK68oUgy8xHxFudFT2LkArLU3YuXCAD10EWxL2gS3bQS+unTeo

      X3Ip0umYx/Iv7ph84iqvPz7zgKCC8gWdRd7IVQIDAQABAoIBAFTcIp+kMzXHzLpg

      9rD3sJ+aYSOX5lzLw9xt1gJ5Qq7Rv8DcxOLiIjS5uh54DP6j92H9uQ0E1v8apVre

      S8apWoeJDvk2J2e21W7g8lfsHdgbnqyWe8XUaV6/nzWF6MPgo/HYYAdy/oRzEiZA

      m36sxHZ2z/9d55mmmjAMlY/wUZPthGt7NK8xy+0t9HROkYl43poFFXT4W2SY5B9E

      UTSA7ZfwvRWCVDMJwU9lh8TzU3zqyXQpRWhgqOwE+SEFylDG/ZCH2FwU30eM0TKU

      kj/JBVbVvvq/34yX5/TDNc1ECZcq7z+BKu1Kc+AovLwKa3eOqF9W3HfLkKyPxUoZ

      RytUV2UCgYEA5suutABMfW1fpUjrCMz2lgdKbKVkbHgX8OcOaGjy2RkUEE729bWT

      HEw3x3el1cgDrenNSYvQrBtKtJW1N9+SAiCzQtZGXQbBFGGDEQeUWE5kL4NyApHP

      LQoQG8G9f6cn8wO6ZUHUnaSTyM7hAbEZTMfj5pJHtyZ/2T8kaONrrfMCgYEA01rQ

      ucwoUvHt49VA5tFp64m2psOgmSCzN2mMktVKzYWUwDx9tfLc+iWlBfUyckulqtD3

      M70n+Smjy4XYuVl4621/qPy9yTBauu2xtPo53FPCdwKNpfbzKv62DOe3hLftELN0

      6IrCPn2aNbXEAjf4UQC3Nm43sJ6kmRZqyN0tmpcCgYBXUmE7QZGvMx6pDrm+jq4N

      fZyvFrS0RYvpXcKZxnt7oH1y3i2aMaUDY+MG2UIpbI/X0UoWtYuyUnElei8igLhh

      jbXFaAUfVVrgNzS70L5T2vUU9QrB5iEYzWHi3p6wGbKHw7VWcl3bd1Vi+MMxPKxx

      3H9h0Z7IsQxWSgmglcs7+QKBgQCLO0dHLnPd+FwTe7eOlqPlM0ps33Cbj4wgU9r0

      G6h0baxJW1AhHYVvEH9+xkFeQ/E17wT6Q4DixgiOGXVk3MkopnCzvRO1RrJudAle

      RHz7ZP41ciwoCd+1EiiRpdAikRuNpfq8+jPuAMYm3b/rCj399q+7Hq53HnsmEjt0

      aSgSrwKBgBvpR8Tzs6ejX+txK+xalWEib1GhRPtNeXuSVaErp+1JDM2Q31lNGN8n

      E/HuJpW0x5PfOBxK/EiwjBrx1B5RLrnjHL+3DkTtZo3WIoKD8Y+o+zY0+0JTT0Qx

      FY2Rj+vlbeGOa/RbMsjezuGDhveqXrdP0/kwlYRj6MLOgVa18BVI

      -----END RSA PRIVATE KEY-----

      '
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+i8DGxrlQabICdAPXUsTDVu+oyj3ydWoszLy4XFECieK1yvxW5Q5iHLTKR2i0sQ1bn4KiKGZFCtqR2/BuWXUXneRJMgJQfCw4k5MSSqgte1qUies3JSNmuekMKF3mmAkS0RCsFDnHVeZh9iOfIpOcEveOGTvkuVAYDpL0UyCoHzNrKbGMsfU129VknKju7MXmiVjBI/gfyD43rpa7/gJWViFfN+J/ZdZfrcPOvTfPBZhB9jVlBYho5pTcHyZNIYrryhSDLzEfEW50VPYuQCstTdi5cIAPXQRbEvaBLdtBL66dN6hfcinS6ZjH8i/umHziKq8/PvOAoILyBZ1F3shV
      Generated by TripleO
  MistralPassword: W4nRztbzMfx7BZe6WWAhuGrv6
  MysqlClustercheckPassword: MeKx4ApKE8nnqchBJVZ6Pmfwb
  MysqlRootPassword: nFts3BHcAd
  NeutronMetadataProxySharedSecret: HwVdGrkP2gQgByQxjvF6B4a3H
  NeutronPassword: 9ZXnCByyWYhxqABVbv6s8fWZy
  NovaPassword: jaYEzwgGjkA8XW32CN3u7V9ue
  NovajoinPassword: 2JKfxvA3pN74K4dwEnMY8ysRy
  OctaviaCaKeyPassphrase: KahCQQuf7rC7jjPTvnUJBCqQb
  OctaviaHeartbeatKey: VynBwJP32tGWt83QvHxBHVej2
  OctaviaPassword: RafuBfcPdEbQ3MZ8RG4pKXMcW
  PacemakerRemoteAuthkey: PkrAfbfbpJBRtUNs6znj4nNBQ3AZHWPysGmvfpGdxBNU3aKZTvaY6g3GZQ2EJftJydWav3tJ8p8M8f72qa2rkvaQCMxWP7Vpj7CqBAZCq7V98TfbU4mFpycMbyRZFj8Y4nhJDJPKtWa4mZZE67wfM9kK73HsThfBHhzBX6HHfxswbJg6P9jtYQRjXdDmsz7276KJqHUswPQYBXppn3T96NuuDyZnzE3J7ZX8Ykye2Zw8XhJeRFayX4agPFMyWeAJkuf3TgYvEXNqrVryVF9MgER8FTADjY8xqWuH6bNJypkeATW7ufKpMwzf29ARrMjghs6AYyX4x6chuEZPBcyP3mPa2NcCkxWxy2KAKNyUF7wjY399U2H4WpHjPB62P3UAEuZ2YqHnh7A7pttmTgcVXMPaFWVxB7bx2mRThD6EpTrZPdsZVFbsMPxcDRPDHss3BNWbBtuRpJbQPhZBzngGrFVF9BCQCcQUctvHWPBpqrHbfaCttYqVVaNUxG24c6AkTReb4WMcBnfemnZbm9mkTNJAmvnymYxdUBPbmEWnYuNT27xHCUDJ7wvqzNWVpYqPJ76vBYBdZFC9UBdcjgxW8gXZy7CE7Ac3cTZr7UC3MCbCq6PPnz8mNRhqgjUxCdkVwQnfs2PJqHBwU8tP9xtBKtQD7CTtnuFqdWudQjtn6krGTxgqBaqqgwpWf6Vq72cQqyxdMYhgrNyDsaJUHCN4zaZpCkPJGsNkvQAssXygExJNUBVeZbCVQFRhHyf7k6aB4ut3cpJBQBzazGyGcWDwgmpRyPjEaqsYxRD6ja6mbQuDF9JJfrx4qxvXwtFGsaPZWYWyzdekv3Y3ZWQKe8Rk2jkGzWYMCtmDfPXJ4fzRFWBQ2vgYWB8baKjv8udhsYfzYn7z8CsvCUCQGZHzW798CtURwjDaRMaexENarRpFUQ9JQzrH3mrdsKKAnTP6KnGFQcPaEer4jFExzJB76acCmZjYDt4VzyZrcsKn2DmWk7keNbE6dGKmrCecvgzaUQRyFhU9sqTCs9AmcWYppdUehJpsjgN7HrshyQesxpxAx7TrTUwEDbWJ9xEE6vfW7VXmpCkmpjunCNdFMD24bReRXVfwJCUvbNRR3FyhxvWwKNj4hNVcdhBZ6qAdBk7TbYufN4sve9aPPmBxAF4tAbDDBNZVd42uTfDsxNP9Y7vHBbuVpQYst2dGrTn7gJEaXeQKdUcz9vHaMnnsmgcuXmWTTf2DZNn6KgAN9qEmm8mgAJgNwU2ZGApWm2PfDanebkvnjBpMvutMhfKxnaJ4hEGyRQDa769sCtmWxnKRjCEsnnyWuwbT7zCJetwAWMJhnAyxNyZPrsCWvW9XQ6WDAEFKg9epdmshdXwbdAqcEhRzcyadYMUPvjWZgmTAwwHFejztkew4hZz2DswF2pANsmbWje9Ttub4k87N3sfqMyzUw7vVP2JEh7jKP6axZk2bfTVepu6bTCEUzGvGuRbbuFvZuWjXPdURp7TwHNjU8JPXgEMagjPaUj6rDH7PPUFxyTrqA4hPkDXMm7dCxcPnqbrwtwJVHJ9bKcMk2hV9D8DhCXAauXDuyBwMfYPa3NwnGfYazP4GdtFEZ4mwhcCpUNJMTeNFmAHjv6X4PdqCuQVzdA7g4XpUEm4UVas6WnxyHWxe6BsaAQKCtbrBf7MKh34DHf26u6gZVWgFJa2JYZaWda6QxrQR4HjFqR48pes8nNK2HzNYVYaprCWDjmB7mwaUMeM2RgEbeFzRsT2hEV4RFh9pydhtgvKbRWvcEbkP8xtzmdd7pqXYmNHcChyxNeUXE2fb2EaAXGrvbXjs3Mkq28ft4C7ebRtbedgnZnZkmWzHTHUxg6YTGZPKPVZDuP9ZkQyhQsFnCUJpBXHrcBBkGfZKtsuQqDpjbbkUwqpwkVFrntvjxtqq37Q4Xp8srEu33QTXyYmaaYr2Dm3xQ74aRRdmsTPvYb4BajzzufBzHykRMfDTVeFesFvzwgXkVh7ZMy6GG4t4YBEECvQBTcV4sbm7agePXjF46yYNkVsAgKhT4YhYJzA2faFeMVan7zsQuJuwApgPx6fvErVY2pCTGU9RxJ49MdsGUj9XRaawxkfcEAj9vGTnqZbzuuqE6wWatK8evT97CUBFaNaHkxzDpzjJtafP67A7HwEcGGekaFryjfCB6uFsYPY2sQ6QRBej8PHABTUsk3hd6V9ccndTQ4huK2nh7e4nFhQftHsJTpxNZgbGFR87P29PQBb8p6ApMWkANxyTBWtgHbATypvkP8afFUWAmRUDjsWgAhQjpv8R4TGc7qJdm9eVJpRGBCJ7GjW6wzbXBkRKFfXWNEERrb8AyukCzc3PaAAJTnBzC9XJ6ZAnMuPauMTktV4zmkysEQyrTxYeBJWdZFdHKgKuysYMKaqZkbAkUq4sDqkEVeevzHQwQjtwBnCHkaxryTRQfMUfsXQmCetPVFzxaU92aFt4b6kkQchqpbxsxVqPZng2FHYewRMyw6Mu3YypdREsTmhwy8JtMURhvUWxz8TWas2mjF86W7HZgvf2ubfPHez4qP9TyfBRQ2MJz2TXuaqrP3twed6tGd9FbbRNTaxFPcsu6d2J7Kyf3tKdfpX8VWy4PPBuA2tNKkrXUFHmAEVneJA9FrqxWspkHcEuUmzUx9U2QtkEgFFxW4BhntgmtvX7wDZPbDnbXW8MkUaesRvhJMcnuMC2gmAY9dpd3nd7YptxGpUAM2RBMWvrAQyJrRzbr3KUm63r7pqFW4xteRQavgMhW77p7MV4qv2a3cPAmQfKXKAAxGYV2e7x6R6G2dGfExyarbmAARK2HrPPUQgwCMwfggRRM6b6NErM49spzxqZcGvsgT4ZG9BgcP8XQtzJjZNx92GREJcFQ3cWWQAMUQfDPFf4aRyc2mBMxbqQHcsQMaVjBpTMVTPWbUZcKw2xhhs4WyzXJNRY7XRAX8qRAZrfqqCwjxBuVNGV7CPMW9fV6rx2MMnYv72YkCHcgYBZy9pmDx6nFaXrkTcyD8mN3kW7Zb2xR8uWPaNVjYWBscB27KYUpnxjVcVyRzAcnt2DmkQPKz8Vhf3NGVFKTY2eE8P4YZgvQvFWUcmYg4h8pzyyVBaY6TYYFfBXRtpDQnyraHKGd8E9HvAzupEZGQhKZweXGpeNdxKKgEYNXJrUekb6pC8aTsKxDh8CVzAkA3aZWpzpPhjyVpjqJxWqHM9VA9MPDXnnjKJF8Jsx96aT78xanK2yPcuyfKpYTxtwCuaB9EkgeeR9wUYCB2ZUmNfHMbKk4EjW3FWCXAAYeRBmEAHRhJhubpmYHkuQHFnWmAPEC2vUPQAr9g9sUHaQMYbeUsb8pxCsKTFYTKBX3CFBZNhHmGYpUEKTpbH7cdTXz9ctvt4cm4xTNvfu4ttPtFyUu6qrReqA6f247s4jWBBrkxVDPFBq6MeTYex84baDfW6hmv8h4sKMkYDwhYpaEZTcDPCjAJGN8AznebTcreGQV7pRe9NMucWUTJbHhnMPJxsTkzperYM6DHa4gfx6KerDkDWkBFCaxDbDcAACGwCfcEJhEWwCYxrcsRQxYheV84KHxTY3cyWKZfmkTT9PjYykEDCvZsWsX8eqyX3gE8wyxhUuHrzdAhkRZFuYXt9XRdaqNBcWdDed4yDcv8kV8b9bGcrrvNqsTgZuRYdXkfFj6JTMhf2nMNfdsXQnptMRGdUTwCqPQHGUnGfzWpMRhCpJnXezDp97XzdFrVPB4Md6NpsGtP4JJXwYXtufaAPAEW9Mfmw2TDDMQDcN7s8d67gWTKBxjhVCZCX4BA9rpzgwAJm7ppfRFFgfP4qfKAhtff6JkDquqJDWa8GavbTFCzsr26fKdFuzTAsuXpwd22rsA8HDmdyAQsGVQWuJxbQacvHJrT34kaVHpjQsFxDmQ8uPCygyMUR9rMKjBjxtG3wUhuWWQBKZY7jkdCTyCFRbfNd8dAwjwsyYvhpfz43bBjjbN662gRB3vq7mR2kXRYdHVh9Zm6uQ98nKQPdktrf38fVdp7GjDhYuBmqANm7nvcPtVFfqZfXexPAfkNsgwvTgVcGcXx3eGP9BffFh3hyP2d9V
  PankoPassword: JYymG6kEUByZ2pdzx6x8AJ9fj
  PcsdPassword: RQNPdVz9Nex4UHRF
  RabbitCookie: wG8gpkJmnubnDQeU8YtG
  RabbitPassword: FCKh6sWBWPW9dA9Ezcee743tt
  RedisPassword: sJ6U2X6sCjugpHzq8xmwurtnx
  SaharaPassword: NZrwD7ej3v8uk2ABQPQdfsJEt
  SnmpdReadonlyUserPassword: 84720f4c29811888b39404412cbcedd12616d70b
  SwiftHashSuffix: dUqWFqg7nkeaRNtPA36Dhfsfd
  SwiftPassword: XRN7weUXwH8rTeFaD8D6cWVeE
  TackerPassword: eAms2DdkfMcXzPCNCKma9TBj2
  TrovePassword: HArBBkQkKda6MygHJCarAmzXM
  ZaqarPassword: fzJvaYpZprC2PuDyzZpPcNKwb
template: overcloud.yaml
version: 1.0
